from pathlib import Path
from tempfile import TemporaryDirectory

from docx import Document
from reportlab.pdfgen.canvas import Canvas

with TemporaryDirectory() as directory:
    root = Path(directory)

    word_path = root / "document.docx"
    word = Document()
    word.add_heading("Hermes document", level=1)
    word.add_paragraph("Generated by python-docx.")
    word.save(word_path)
    assert word_path.read_bytes().startswith(b"PK\x03\x04")

    pdf_path = root / "document.pdf"
    pdf = Canvas(str(pdf_path))
    pdf.drawString(72, 720, "Hermes document")
    pdf.save()
    assert pdf_path.read_bytes().startswith(b"%PDF-")

print("document_runtime=PASS")
